# https://github.com/pages-themes/cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: typescript-utilities by Y-Walter
description: Utilities for TypeScript in Personal Use

docs_list_title: typescript-utilities by Y-Walter
docs:
  - title: Introduction
    url: index.md
  
  - title: Get Started
    url: getStarted/index.md
