name: Check Lib

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: lib/package.json
          cache: npm
          cache-dependency-path: lib/package-lock.json
      
      - name: Install
        run: npm ci --prefix lib
      
      - name: Lint
        run: npm run lint --prefix lib

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: lib/package.json
          cache: npm
          cache-dependency-path: lib/package-lock.json
      
      - name: Install
        run: npm ci --prefix lib
      
      - name: Test
        run: npm run test --prefix lib
