name: Check Lib

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: lib/package.json
          cache: npm
          cache-dependency-path: lib/package-lock.json
      
      - name: Install
        run: npm ci --prefix lib
      
      - name: Lint
        run: npm run lint --prefix lib

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: lib/package.json
          cache: npm
          cache-dependency-path: lib/package-lock.json
      
      - name: Install
        run: npm ci --prefix lib
      
      - name: Test
        run: npm run test --prefix lib
